# 此文件为页面的配置文件，所有需要填写的标签的标签类型与定位方式均按指定格式编写
#
# 定位方式可选以下8种，推荐用id：
# "id"    "xpath"     "link text"   "partial link text"
# "name"  "tag name"  "class name"  "css selector"
#
# 操作指令可选以下5种：
# select    sendkeys    click   clear   submit    readonly_input

---
# 配置节，必须为第一节！
browser: chrome  # 可选firefox、chrome，若为chrome，则需在当前文件夹下添加chromedriver.exe
#location: C:\\Program Files\\Mozilla Firefox\\firefox.exe  # 浏览器位置，不写这项配置则为默认路径
delay_submit: 5  # 延时提交，每次提交之前等待xx秒
if_wait: 3  # 判断页面url前等待时间，默认3秒
#random_agent_spoofer: '..\random-agent-spoofer.xpi'
proxy: False
proxytool: 'C:\\jk\\ProxyTool\\AutoProxyTool.exe'
ipchecker: 'http://173.230.146.56/ip/getip.php'

---
# 接下来的均为任务节
- url: https://www.cashadvance.com/
- sheet: cashadvance

# [定位方式, 定位表达式, 动作, 名称（对应Excel中列名）]
- elements:
#    - {switch: 0}  # 可以是frame的id，name，或者序号（从0开始）
#    - {switch: 'default_content'}  # default_content表示切回主文档
    - ['id', 'amount', select, ['100','200','300','400','500']]
    - ['id', 'zip', sendkeys, zip]
    - ['id', 'firstName', sendkeys, first_name]
    - ['id', 'lastName', sendkeys, last_name]
    - ['id', 'email', sendkeys, email]
    - ['id', 'cta-submit', submit, submit_1]

- elements:
    - {if: 'www.cawwwsh', action: go, else: skip}
    - {wait: [2, 5]}
    - ['id', 'address', sendkeys, address]
    - {if: 'www.cash', action: go, else: skip}
    - ['id', 'lengthAtAddress', select, random]
    - ['id', 'rentOwn', select, random]
    - ['id', 'license', sendkeys, dlnumber]
    - ['id', 'licenseState', select, dlstate]
    - ['id', 'ownCar', select, ['yes']]
    - ['id', 'phone', sendkeys, homephone]
    - ['id', 'callTime', select, random]
    - ['id', 'bMonth', select, bMonth]
    - ['id', 'bDay', select, bDay]
    - ['id', 'bYear', select, bYear]
    - ['id', 'ssn', sendkeys, ssn]
    - ['id', 'nextButton', click, nextButton]

- elements:
    - {wait: [2, 5]}
    - {if: 'www.a.com', action: go, else: skip}
    - ['id', 'armedForces', select, ['no']]
    - ['id', 'incomeSource', select, ['EMPLOYMENT']]
    - {if: 'www.b.com', action: go, else: skip}
    - ['id', 'employerName', sendkeys, employer_name]
    - ['id', 'timeEmployed', select, random]
    - {if: 'www.c.com', action: go}
    - ['id', 'employerPhone', sendkeys, workphone]
    - ['id', 'jobTitle', sendkeys, job_title]
    - ['id', 'paidEvery', select, random]
    - ['id', 'nextPayday', clear, nextPayday]
    - ['id', 'nextPayday', readonly_input, readonly]
    - ['id', 'abaNumber', sendkeys, routingnumber]
    - ['id', 'accountNumber', sendkeys, accountnumber]
    - ['id', 'accountType', select, ['checking']]
    - ['id', 'monthsBank', select, random]
    - ['id', 'directDeposit', select, ['yes']]
    - ['id', 'monthlyNetIncome', select, random]
    - ['id', 'submitButton', click, submitButton]

